### ISSUE TITLE
隔天连接失败

### ISSUE THREAD

**Issue by teryt-fu** [Safe3/firefly#17]
使用最新版本，昨天使用正常。终端关闭连接后，今天尝试开启，无法连接。重启服务、重装终端后仍然无法解决

**Comment by Safe3** [comment]
由于使用的是原版wireguard协议，只适合在国内使用，服务器位于国外会再出现端口被封情况

**Comment by teryt-fu** [comment]
> 由于使用的是原版wireguard协议，只适合在国内使用，服务器位于国外会出现端口被封的情况

thanks

**Comment by passiolin** [comment]
doge，看了下基于wireguard，原本还想看下怎么避免端口和ip被封的问题，原来是避免不了的
