### ISSUE TITLE
没有预共享密钥配置。

### ISSUE THREAD

**Issue by hkthomas** [Safe3/firefly#4]
按照配置文件手动增加也识别不出来，能否麻烦加上这个对应配置呢。

**Comment by Safe3** [comment]
暂时优先级不高，后续看情况，你也可以贡献代码

**Comment by hkthomas** [comment]
好的老哥。

**Comment by Amaan1532** [comment]
> 按照配置文件手动增加也识别不出来，能否麻烦加上这个对应配置呢。

Please tell me in English
