### ISSUE TITLE
只能连上一台

### ISSUE THREAD

**Issue by kof8855** [Safe3/firefly#7]
创了3个终端，一个笔记本 一个电脑 一个手机，只有笔记本能连上，电脑和手机状态都只有发送没有接收。

**Comment by Safe3** [comment]
正常应该都可以连才对

**Comment by kof8855** [comment]
> 正常应该都可以连才对

连得上是没错，但是电脑和手机状态都只有发送没有接收，完全打不开任何东西，但是笔记本就可以正常使用开网页 查IP归属也是我的阿里云服务器了。家里同一个网络下这样、即使手机用4G信号也还是这样。有没有可以查看的日志输出

![image](https://github.com/Safe3/firefly/assets/57129756/47441a18-0c48-40a3-af33-f909c7a01661)

**Comment by Safe3** [comment]
如果服务器使用的是各种云服务，记得在云服务管理后台上开放萤火虫所需的udp端口50120、tcp端口50121

**Comment by kof8855** [comment]
> 如果服务器使用的是各种云服务，记得在云服务管理后台上开放萤火虫所需的udp端口50120、tcp端口50121

端口全部开放的，只对22端口做了iptables访问限制。没有解决思路的话，我只能换回原版的wireguard来搭建了，之前用得没问题
